"""库名映射器和 API 说明"""
LIBRARY_MAP = {
    # C++
    'cv::': 'OpenCV',
    'pcl::': 'PCL',
    'Eigen::': 'Eigen',
    'g2o::': 'g2o',
    'DBoW2::': 'DBoW2',
    'std::': 'STL',
    'boost::': 'Boost',
    # Python
    'cv2.': 'OpenCV',
    'np.': 'NumPy',
    'pd.': 'Pandas',
    'plt.': 'Matplotlib',
    'torch.': 'PyTorch',
    'tf.': 'TensorFlow',
    # JavaScript
    'console.': 'JavaScript',
    'document.': 'DOM',
    'Math.': 'JavaScript',
    'Array.': 'JavaScript',
    'Object.': 'JavaScript',
    'Promise.': 'JavaScript',
    'JSON.': 'JavaScript',
    # TypeScript
    'process.': 'Node.js',
}

# API 说明库（常见函数的简要说明）
API_DESCRIPTIONS = {
    # OpenCV
    'cv::imread': '从文件读取图像，支持 PNG/JPG/BMP 等格式',
    'cv::resize': '调整图像尺寸，常用于图像预处理',
    'cv::cvtColor': '颜色空间转换，如 BGR 转 GRAY',
    'cv::GaussianBlur': '高斯模糊，用于降噪',
    'cv::Canny': 'Canny 边缘检测',
    'cv::findContours': '查找图像轮廓',
    'cv::drawContours': '绘制轮廓',
    'cv::waitKey': '等待键盘输入，常用于显示窗口的刷新',
    'cv::namedWindow': '创建命名窗口',
    'cv::imshow': '在窗口中显示图像',
    'cv::remap': '图像重映射，用于校正畸变',
    'cv::undistort': '去畸变校正',
    'cv::Mat': 'OpenCV 核心矩阵类型，存储图像数据',
    'cv::Point': '二维点坐标',
    'cv::Size': '尺寸结构体',
    'cv::Rect': '矩形区域',
    'cv::Scalar': '四通道标量值',
    'cv::circle': '画圆',
    'cv::line': '画直线',
    'cv::rectangle': '画矩形',
    'cv::putText': '在图像上绘制文字',
    'cv::getRotationMatrix2D': '获取旋转变换矩阵',
    'cv::warpAffine': '仿射变换',
    'cv::warpPerspective': '透视变换',
    'cv::threshold': '阈值分割',
    'cv::adaptiveThreshold': '自适应阈值分割',
    'cv::blur': '均值模糊',
    'cv::medianBlur': '中值模糊',
    'cv::bilateralFilter': '双边滤波器，保边降噪',
    'cv::morphologyEx': '形态学操作（开/闭/梯度等）',
    'cv::erode': '腐蚀操作',
    'cv::dilate': '膨胀操作',
    'cv::matchTemplate': '模板匹配',
    'cv::minMaxLoc': '查找矩阵中的最小/最大值',
    'cv::normalize': '归一化数组',
    'cv::transpose': '矩阵转置',
    'cv::flip': '图像翻转',
    'cv::rotate': '图像旋转',
    'cv::hconcat': '水平拼接图像',
    'cv::vconcat': '垂直拼接图像',
    'cv::absdiff': '计算两个数组的绝对差',
    'cv::addWeighted': '图像加权融合',
    'cv::bitwise_and': '按位与运算',
    'cv::bitwise_or': '按位或运算',
    'cv::bitwise_xor': '按位异或运算',
    'cv::bitwise_not': '按位取反',
    'cv::reduce': '矩阵降维',
    'cv::split': '分离多通道图像',
    'cv::merge': '合并通道为多通道图像',
    'cv::abs': '计算绝对值',
    'cv::sqrt': '计算平方根',
    'cv::pow': '幂运算',
    'cv::log': '对数运算',
    'cv::exp': '指数运算',
    'cv::convertScaleAbs': '缩放、转换并取绝对值',
    'cv::HOGDescriptor': 'HOG 特征描述符',
    'cv::ORB': 'ORB 特征检测器',
    'cv::AKAZE': 'AKAZE 特征检测器',
    'cv::BFMatcher': '暴力匹配器',
    'cv::FlannBasedMatcher': 'FLANN 近似最近邻匹配器',
    'cv::drawMatches': '绘制特征匹配结果',
    'cv::matchShapes': '形状匹配',
    'cv::Moments': '计算图像矩',
    'cv::contourArea': '计算轮廓面积',
    'cv::arcLength': '计算轮廓周长',
    'cv::boundingRect': '计算边界矩形',
    'cv::minAreaRect': '计算最小面积矩形',
    'cv::fitLine': '直线拟合',
    'cv::fitEllipse': '椭圆拟合',
    'cv::approxPolyDP': '多边形逼近',
    'cv::convexHull': '计算凸包',
    'cv::isContourConvex': '判断轮廓是否为凸',
    'cv::pointPolygonTest': '点是否在轮廓内',
    'cv::VideoCapture': '视频捕获对象',
    'cv::VideoWriter': '视频写入对象',
    'cv::FileStorage': '文件存储（YAML/XML）',
    'cv::FileNode': '文件存储节点',

    # PCL
    'pcl::PassThrough': '直通滤波，在指定范围内保留点',
    'pcl::VoxelGrid': '体素网格滤波，下采样',
    'pcl::StatisticalOutlierRemoval': '统计离群点移除',
    'pcl::RadiusOutlierRemoval': '半径离群点移除',
    'pcl::ConditionalRemoval': '条件滤波',
    'pcl::ExtractIndices': '根据索引提取点云',
    'pcl::CropBox': '箱体裁剪',
    'pcl::CropHull': ' hull 裁剪',
    'pcl::PointCloud': '点云数据结构',
    'pcl::visualization::PCLVisualizer': 'PCL 可视化查看器',
    'pcl::visualization::PointCloudColorHandler': '点云颜色处理器',
    'pcl::visualization::RangeImageVisualizer': '深度图像可视化',
    'pcl::io::savePCDFile': '保存 PCD 点云文件',
    'pcl::io::loadPCDFile': '加载 PCD 点云文件',
    'pcl::io::savePLYFile': '保存 PLY 点云文件',
    'pcl::io::loadPLYFile': '加载 PLY 点云文件',
    'pcl::console::print_error': '打印错误信息',
    'pcl::console::print_info': '打印普通信息',
    'pcl::console::print_warn': '打印警告信息',
    'pcl::console::parse_argument': '解析命令行参数',

    # Eigen
    'Eigen::Matrix': 'Eigen 矩阵类型',
    'Eigen::Vector': 'Eigen 向量类型',
    'Eigen::Map': '映射外部数据为 Eigen 类型',
    'Eigen::IOFormat': '矩阵输出格式',
    'Eigen::AngleAxisd': '旋转向量（轴角表示）',
    'Eigen::Translation3d': '平移向量',
    'Eigen::Isometry3d': '3D 等距变换（旋转+平移）',
    'Eigen::Affine3d': '3D 仿射变换',
    'Eigen::Quaterniond': '四元数',
    'Eigen::Matrix3d': '3x3 double 矩阵',
    'Eigen::Vector3d': '3维 double 向量',
    'Eigen::Matrix4d': '4x4 double 矩阵',
    'Eigen::ColPivHouseholderQR': '列主元 QR 分解',
    'Eigen::FullPivLU': '完全主元 LU 分解',
    'Eigen::JacobiSVD': '奇异值分解',
    'Eigen::computeAngleAxis': '从四元数计算轴角',
    'Eigen::AngleAxisp::FromTwoVectors': '从两个向量计算旋转',

    # g2o
    'g2o::OptimizationAlgorithmLevenberg': 'Levenberg-Marquardt 优化算法',
    'g2o::OptimizationAlgorithmGaussNewton': '高斯牛顿优化算法',
    'g2o::OptimizationAlgorithmDogleg': 'Dogleg 优化算法',
    'g2o::VertexSE3': 'SE(3) 位姿顶点（6自由度）',
    'g2o::VertexSE3Expmap': 'SE(3) 指数映射顶点',
    'g2o::VertexPointXYZ': '3D 点顶点',
    'g2o::VertexSBAPointXYZ': 'SBA 3D 点顶点',
    'g2o::VertexSim3': 'Sim(3) 相似变换顶点',
    'g2o::VertexSim3Expmap': 'Sim(3) 指数映射顶点',
    'g2o::EdgeSE3': 'SE(3) 边',
    'g2o::EdgeSE3ProjectXYZ': '带相机投影的 SE(3) 边',
    'g2o::EdgeSim3': 'Sim(3) 边',
    'g2o::BlockSolver': '块求解器基类',
    'g2o::BlockSolver_6_3': 'BlockSolver（6维位姿+3维点）',
    'g2o::BlockSolver_7_3': 'BlockSolver（7维Sim3+3维点）',
    'g2o::BlockSolverX': '通用 BlockSolver',
    'g2o::LinearSolver': '线性求解器基类',
    'g2o::LinearSolverCSparse': 'CSparse 线性求解器',
    'g2o::LinearSolverCholmod': 'CHOLMOD 线性求解器',
    'g2o::SparseOptimizer': '稀疏优化器',
    'g2o::initializeOptimization': '初始化优化',
    'g2o::optimize': '执行优化',
    'g2o::computeActiveErrors': '计算活跃边的误差',
    'g2o::setVerbose': '设置详细输出',
    'g2o::setMethod': '设置优化方法',
    'g2o::addVertex': '添加顶点',
    'g2o::addEdge': '添加边',
    'g2o::edge': '获取边',
    'g2o::vertex': '获取顶点',
    'g2o::eraseEdge': '删除边',
    'g2o::clear': '清空优化器',
    'g2o::save': '保存图到文件',
    'g2o::load': '从文件加载图',
    'g2o::get_time': '获取当前时间（秒）',

    # DBoW2
    'DBoW2::ORBVocabulary': 'ORB 词袋 vocabulary',
    'DBoW2::ORBDatabase': 'ORB 特征数据库',
    'DBoW2::TemplatedVocabulary': '模板化词袋基类',
    'DBoW2::TemplatedDatabase': '模板化数据库基类',
    'DBoW2::ScoringObject': '评分对象基类',
    'DBoW2::L1Scoring': 'L1 范数评分',
    'DBoW2::L2Scoring': 'L2 范数评分',
    'DBoW2::ChiScoring': '卡方评分',
    'DBoW2::KLScoring': 'KL 散度评分',
    'DBoW2::HammingScoring': '汉明距离评分',

    # STL
    'std::vector': '动态数组容器',
    'std::map': '有序键值对容器',
    'std::unordered_map': '哈希键值对容器',
    'std::set': '有序集合容器',
    'std::unordered_set': '哈希集合容器',
    'std::list': '双向链表容器',
    'std::deque': '双端队列容器',
    'std::queue': '队列容器',
    'std::stack': '栈容器',
    'std::pair': '二元组',
    'std::tuple': '多元组',
    'std::make_pair': '创建 pair',
    'std::make_tuple': '创建 tuple',
    'std::cout': '标准输出流',
    'std::cerr': '标准错误流',
    'std::cin': '标准输入流',
    'std::string': '字符串类型',
    'std::thread': '线程',
    'std::mutex': '互斥锁',
    'std::lock_guard': '互斥锁守卫（RAII 锁）',
    'std::unique_lock': '唯一锁',
    'std::condition_variable': '条件变量',
    'std::async': '异步执行函数',
    'std::future': '异步结果',
    'std::promise': '异步承诺',
    'std::shared_ptr': '共享指针',
    'std::unique_ptr': '独占指针',
    'std::weak_ptr': '弱引用指针',
    'std::enable_shared_from_this': '启用从 this 创建 shared_ptr',
    'std::make_shared': '创建 shared_ptr',
    'std::static_pointer_cast': '静态指针转换',
    'std::dynamic_pointer_cast': '动态指针转换',
    'std::function': '函数包装器',
    'std::bind': '绑定函数参数',
    'std::thread::sleep_for': '线程休眠',
    'std::this_thread::get_id': '获取当前线程 ID',
    'std::chrono::steady_clock': '稳定时钟',
    'std::chrono::system_clock': '系统时钟',
    'std::chrono::duration': '时间长度',
    'std::chrono::time_point': '时间点',
    'std::chrono::high_resolution_clock': '高精度时钟',
    'std::numeric_limits': '数值类型限制',
    'std::abs': '绝对值',
    'std::max': '最大值',
    'std::min': '最小值',
    'std::swap': '交换两个值',
    'std::sort': '排序',
    'std::reverse': '反转',
    'std::find': '查找元素',
    'std::count': '计数',
    'std::accumulate': '累加',
    'std::transform': '变换',
    'std::for_each': '对每个元素执行操作',
    'std::fill': '填充',
    'std::copy': '复制',
    'std::move': '移动语义',
    'std::unique': '去重',
    'std::lower_bound': '下界查找',
    'std::upper_bound': '上界查找',
    'std::binary_search': '二分查找',
    'std::next_permutation': '下一个排列',
    'std::prev_permutation': '上一个排列',

    # Boost
    'boost::bind': '绑定函数/参数到可调用对象',
    'boost::function': '函数对象包装器',
    'boost::make_shared': '创建 boost shared_ptr',
    'boost::shared_ptr': 'Boost 共享指针',
    'boost::weak_ptr': 'Boost 弱引用指针',
    'boost::scoped_ptr': 'boost 独占指针（非复制）',
    'boost::ref': '创建引用包装器',
    'boost::numeric::ublas': 'Boost 数值库（矩阵/向量）',
    'boost::filesystem::path': '文件系统路径',
    'boost::filesystem::exists': '检查路径是否存在',
    'boost::filesystem::create_directory': '创建目录',
    'boost::filesystem::remove': '删除文件',
    'boost::filesystem::copy_file': '复制文件',
    'boost::filesystem::directory_iterator': '目录迭代器',
    'boost::thread': 'Boost 线程',
    'boost::mutex': 'Boost 互斥锁',
    'boost::timed_mutex': '带超时的互斥锁',
    'boost::recursive_mutex': '递归互斥锁',
    'boost::lock_guard': 'Boost 互斥锁守卫',
    'boost::unique_lock': 'Boost 唯一锁',
    'boost::condition_variable': 'Boost 条件变量',
    'boost::this_thread::sleep': '线程休眠',
    'boost::this_thread::get_id': '获取线程 ID',
    'boost::format': '格式化字符串',
    'boost::lexical_cast': '类型转换',
    'boost::any': '任意类型容器',
    'boost::variant': '变体类型',
    'boost::optional': '可选值容器',
    'boost::tokenizer': '字符串分词器',
    'boost::regex': '正则表达式',
    'boost::date_time': '日期时间处理',
    'boost::pool': '内存池',
    'boost::circular_buffer': '环形缓冲区',
    'boost::circular_buffer_space_optimized': '空间优化环形缓冲区',
    'boost::interprocess::vector': '进程间通信向量',
    'boost::interprocess::map': '进程间通信映射',
    'boost::interprocess::shared_memory_object': '共享内存对象',
    'boost::interprocess::mapped_region': '映射区域',
}


def get_library_name(prefix: str) -> str:
    return LIBRARY_MAP.get(prefix, 'Unknown')


def get_api_description(func_name: str) -> str:
    """获取 API 的简要说明"""
    return API_DESCRIPTIONS.get(func_name, '（待补充）')
